### ISSUE TITLE
Suggestion: Disable Mod name from WAILA display

### ISSUE THREAD

**Issue by jason-pollak** [Vazkii/crucia2-issues#10]
I've turned off the mod name in WAILA, as I find that seeing the name gets in the way of immersion, and makes the game feel less cohesive. If I want to know what mod something is from, JEI has it listed. In his (your?) BlockTalk appearance, Vaz talked about hating WAILA, and this achieves the best of both worlds.

**Comment by Vazkii** [comment]
While I do like the idea, it ends up looking weird with nothing under it
![image](https://user-images.githubusercontent.com/1794735/107084664-41941300-67ef-11eb-9026-1dfd54d9e3d5.png)
