### ISSUE TITLE
JEI search category "Useful Items" instead of "Utility Items"

### ISSUE THREAD

**Issue by iGalaxyYT** [Vazkii/crucia2-issues#11]
In the guidebook, it references a "Utility Items" category, but when you try to search it up, nothing comes up. I experimented for a bit and found that it's actually "Useful Items" instead of what's written in the guidebook.
![image](https://user-images.githubusercontent.com/22878174/106989870-f662fd00-6727-11eb-8ed7-df473cc247cd.png)
![image](https://user-images.githubusercontent.com/22878174/106989885-fc58de00-6727-11eb-891c-e9528c156e47.png)
![image](https://user-images.githubusercontent.com/22878174/106989906-07137300-6728-11eb-9006-c750f0362457.png)

**Comment by Vazkii** [comment]
Fixed
