### ISSUE TITLE
Bat in a bucket and Coral Squid in a bucket aren't consistent with other bucket names

### ISSUE THREAD

**Issue by Carmenboy1** [Vazkii/crucia2-issues#12]
Instead of "Bucket of Squid/Bat" its "Bat/Squid in a bucket" (also the name "squid in the bucket" implies its a normal squid despite it being a coral squid, so that might need to be fixed too)

**Comment by Vazkii** [comment]
The coral squid isn't enabled. You won't find it in JEI for that reason. Unfortunately, items in creative can't really be disabled that easily.

**Comment by Vazkii** [comment]
Fixed the bat one
