### ISSUE TITLE
Cannot close recipe book in inventory without portable crafting.

### ISSUE THREAD

**Issue by SwanX1** [Vazkii/crucia2-issues#13]
Steps to reproduce:
1. Get a crafting table to get portable crafting
2. Open recipe book
3. Remove crafting table from inventory
4. You are now stuck with recipe book until you open portable crafting again (poor design imo)

**Comment by Vazkii** [comment]
fixd

**Comment by SwanX1** [comment]
not fixed in beta8 but ok sure
