### ISSUE TITLE
Warped Garden Generation disabled, but advancement still exists

### ISSUE THREAD

**Issue by CosmicParticl** [Vazkii/crucia2-issues#14]
It'd probably be a good idea to get rid of that so people don't get confused with an unobtainable advancement.

**Comment by CosmicParticl** [comment]
While you are at it, perhaps disable the advancements for things such as disabled mobs from Alex's mobs. Unobtainable advancements are always irksome.

**Comment by Vazkii** [comment]
List of advancements to remove so I don't forget later:

Alex's Mobs:
* Gone Bananas
* In Memoriam
* Monkey Business
* Uma Delicia

Dungeons Plus
* Something Unnatural

**Comment by Vazkii** [comment]
Done. Was slightly easier than I thought.
