### ISSUE TITLE
Crash on world startup

### ISSUE THREAD

**Issue by Quadae** [Vazkii/crucia2-issues#15]
---- Minecraft Crash Report ----
// My bad.

Time: 2/7/21 12:49 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at hunternif.mc.impl.atlas.marker.GlobalMarkersDataHandler.onPlayerLogin(GlobalMarkersDataHandler.java:59) ~[antiqueatlas:?] {re:classloading}
	at hunternif.mc.impl.atlas.forge.ForgeEvent.playerJoin(ForgeEvent.java:51) ~[antiqueatlas:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_243_ForgeEvent_playerJoin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:endergetic.mixins.json:PlayerListMixin,pl:mixin:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 678286816 bytes (646 MB) / 3755999232 bytes (3582 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		StructuredCrafting-1.16.4-0.2.2.jar               |StructuredCrafting            |structuredcrafting            |0.2.2               |DONE      |NOSIGNATURE
		CyclopsCore-1.16.4-1.11.1.jar                     |Cyclops Core                  |cyclopscore                   |1.11.1              |DONE      |NOSIGNATURE
		SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |DONE      |NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |NOSIGNATURE
		Notes-1.16.4-1.2.3.jar                            |Notes                         |notes                         |1.16.4-1.2.3        |DONE      |NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		fish_in_planks-1.16.4-0.2.jar                     |Fish in Planks                |fish_in_planks                |1.16.4-0.2          |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		berry_good-1.16.4-4.0.0.jar                       |Berry Good                    |berry_good                    |4.0.0               |DONE      |NOSIGNATURE
		Enhanced-Mushrooms-1.16.4-3.0.3.jar               |Enhanced Mushrooms            |enhanced_mushrooms            |1.16.4-3.0.3        |DONE      |NOSIGNATURE
		glazedsymmetry-1.0.jar                            |Glazed Symmetry               |glazedsymmetry                |1.0                 |DONE      |NOSIGNATURE
		Better-Badlands-1.16.5-2.0.2.jar                  |Better Badlands               |better_badlands               |1.16.5-2.0.2        |DONE      |NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |DONE      |NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		shutupexperimentalsettings-1.0.1.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.1               |DONE      |NOSIGNATURE
		Controlling-7.0.0.11.jar                          |Controlling                   |controlling                   |7.0.0.11            |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.5.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.5.0               |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		fantasy-forge-1.0.2b.jar                          |Fantasy Mounts                |fantasy                       |1.0                 |DONE      |NOSIGNATURE
		environmental-1.16.4-1.0.0-f179725070e0490ca3deefe|Environmental                 |environmental                 |1.0.0               |DONE      |NOSIGNATURE
		Bookshelf-1.16.4-9.3.25.jar                       |Bookshelf                     |bookshelf                     |9.3.25              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		itemzoom-1.16.x-2.2.1.jar                         |Item Zoom Rekindled           |itemzoom                      |2.2.1               |DONE      |NOSIGNATURE
		forgery-1.3.1.jar                                 |Fabrication                   |fabrication                   |1.3.1               |DONE      |NOSIGNATURE
		guardvillagers-1.16.4-1.1.8.jar                   |Guard Villagers               |guardvillagers                |1.1.8               |DONE      |NOSIGNATURE
		bedspreads-forge-1.16.4-5.1.0.1.jar               |Bedspreads                    |bedspreads                    |1.16.4-5.1.0.1      |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |DONE      |NOSIGNATURE
		SnowRealMagic-1.16.4-2.3.0.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.3.0               |DONE      |NOSIGNATURE
		Kiwi-1.16.3-3.4.1.jar                             |Kiwi                          |kiwi                          |3.4.1               |DONE      |NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.11.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.11            |DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.117.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.117           |DONE      |NOSIGNATURE
		panorama-1.1.jar                                  |Panorama                      |panorama                      |1.0.0               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		supplementaries-1.16.5-0.9.23c.jar                |Supplementaries               |supplementaries               |1.16.5-0.9.23c      |DONE      |NOSIGNATURE
		nether_extension-1.16.4-0.3.0.jar                 |Nether Extension              |nether_extension              |1.16.4-0.3.0        |DONE      |NOSIGNATURE
		neapolitan-1.16.4-2.0.1.jar                       |Neapolitan                    |neapolitan                    |2.0.1               |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.8.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.8      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.1.0.jar                       |The Endergetic Expansion      |endergetic                    |3.1.0               |DONE      |NOSIGNATURE
		FarmersDelight-1.16.3-0.3.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.3.2        |DONE      |NOSIGNATURE
		customizableelytra-1.16.4-1.0.2.jar               |Customizable Elytra           |customizableelytra            |1.1                 |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		dungeons_plus-1.16.4-1.1.3.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.3               |DONE      |NOSIGNATURE
		skinned_lanterns-1.16.4-1.3.1.jar                 |Skinned Lanterns              |skinnedlanterns               |1.16.4-1.3.1        |DONE      |NOSIGNATURE
		lepton-1.16.4-1.2.5.jar                           |Lepton                        |lepton                        |1.2.5               |DONE      |NOSIGNATURE
		atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		Mantle-1.16.5-1.6.79.jar                          |Mantle                        |mantle                        |1.6.79              |DONE      |NOSIGNATURE
		Inspirations-1.16.5-1.2.2.jar                     |Inspirations                  |inspirations                  |1.2.2               |DONE      |NOSIGNATURE
		leap-1.16.4-1.0.1.jar                             |Leap                          |leap                          |1.0.1               |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		autumnity-1.16.4-2.0.1.jar                        |Autumnity                     |autumnity                     |2.0.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-303.jar                                |Quark                         |quark                         |r2.4-303            |DONE      |NOSIGNATURE
		illagersweararmor-1.0.4.jar                       |Illagers Wear Armor           |illagersweararmor             |1.0.4               |DONE      |NOSIGNATURE
		travelers_index-1.16.4-1.0.2.jar                  |Traveler's Index              |travelers_index               |1.16.4-1.0.2        |DONE      |NOSIGNATURE
		sapience-1.16.4-1.1.1.jar                         |Sapience                      |sapience                      |1.1.1               |DONE      |NOSIGNATURE
		architectury-1.5.106-forge.jar                    |Architectury                  |architectury                  |1.5.106             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.38-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.38         |DONE      |NOSIGNATURE
		Chimes-1.16.5-0.9.5.jar                           |Chimes                        |chimes                        |0.9.5               |DONE      |NOSIGNATURE
		charm-forge-1.16.4-2.2.2.jar                      |Charm                         |charm                         |2.2.2               |DONE      |NOSIGNATURE
		charmonium-forge-1.16.4-2.2.2.jar                 |Charmonium                    |charmonium                    |2.2.1               |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		step-1.16.4-1.0.3.jar                             |Step                          |step                          |1.0.3               |DONE      |NOSIGNATURE
		OpenLoader-1.16.4-8.0.3.jar                       |OpenLoader                    |openloader                    |8.0.3               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
	Crash Report UUID: a7b071c8-4f15-4e96-95ac-521aa7ef75b1
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:world
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['Quadae'/115, l='ServerLevel[Beta Gaming]', x=-582.42, y=16.22, z=309.37]]
	Data Packs: vanilla, mod:structuredcrafting, mod:cyclopscore, mod:savemystronghold, mod:quarkoddities (incompatible), mod:notes (incompatible), mod:spiderstpo, mod:jei, mod:fish_in_planks, mod:abnormals_core, mod:buzzier_bees, mod:berry_good, mod:enhanced_mushrooms, mod:glazedsymmetry, mod:better_badlands, mod:extraboats, mod:neat (incompatible), mod:bettercaves (incompatible), mod:shutupexperimentalsettings (incompatible), mod:controlling, mod:placebo (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:yungsapi, mod:fantasy, mod:environmental, mod:bookshelf, mod:itemzoom (incompatible), mod:fabrication, mod:guardvillagers, mod:bedspreads, mod:waila, mod:toastcontrol (incompatible), mod:snowrealmagic, mod:kiwi (incompatible), mod:jeitweaker, mod:crafttweaker, mod:panorama, mod:forge, mod:supplementaries, mod:nether_extension, mod:neapolitan, mod:dsurround, mod:structure_gel, mod:antiqueatlas, mod:upgrade_aquatic, mod:endergetic, mod:farmersdelight, mod:customizableelytra, mod:mousetweaks, mod:dungeons_plus, mod:skinnedlanterns, mod:lepton, mod:atmospheric, mod:savageandravage, mod:patchouli (incompatible), mod:mantle (incompatible), mod:inspirations (incompatible), mod:leap (incompatible), mod:ftbbackups (incompatible), mod:autumnity, mod:autoreglib (incompatible), mod:quark (incompatible), mod:illagersweararmor (incompatible), mod:travelers_index (incompatible), mod:sapience, mod:architectury, mod:ftbguilibrary (incompatible), mod:chimes, mod:charm (incompatible), mod:charmonium (incompatible), mod:bettermineshafts (incompatible), mod:step (incompatible), mod:openloader, openloader/data/crucial_data, openloader/data/crucial_worldgen
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Vazkii** [comment]
You should report this directly to antique atlas.
