### ISSUE TITLE
[Suggestion] JEI Search Suggestion: "Light Sources"

### ISSUE THREAD

**Issue by AstroCat2Space** [Vazkii/crucia2-issues#16]
After discovering all of these recipes for lamps, torches, and other light sources, I have a suggestion for a JEI search category: "light sources", which will show all items/blocks that emit light. What do you think?

**Comment by MaxKelton** [comment]
I believe this is all light sources as of beta-8
`minecraft:glowstone
minecraft:jack_o_lantern
minecraft:sea_lantern
minecraft:magma_block
minecraft:torch
minecraft:sea_pickle
minecraft:soul_torch
minecraft:ender_chest
minecraft:lantern
minecraft:soul_lantern
minecraft:campfire
minecraft:soul_campfire
minecraft:shroomlight
minecraft:redstone_torch
minecraft:respawn_anchor
minecraft:beacon
minecraft:flint_and_steel
minecraft:conduit
minecraft:lava_bucket
better_badlands:terracotta_lamp
better_badlands:black_terracotta_lamp
better_badlands:brown_terracotta_lamp
better_badlands:red_terracotta_lamp
better_badlands:green_terracotta_lamp
better_badlands:blue_terracotta_lamp
better_badlands:purple_terracotta_lamp
better_badlands:cyan_terracotta_lamp
better_badlands:light_gray_terracotta_lamp
better_badlands:gray_terracotta_lamp
better_badlands:pink_terracotta_lamp
better_badlands:lime_terracotta_lamp
better_badlands:yellow_terracotta_lamp
better_badlands:light_blue_terracotta_lamp
better_badlands:magenta_terracotta_lamp
better_badlands:orange_terracotta_lamp
better_badlands:white_terracotta_lamp
buzzier_bees:candle
buzzier_bees:soul_candle
buzzier_bees:ender_candle
buzzier_bees:white_candle
buzzier_bees:orange_candle
buzzier_bees:magenta_candle
buzzier_bees:light_blue_candle
buzzier_bees:yellow_candle
buzzier_bees:azure_bluet_scented_candle
buzzier_bees:allium_scented_candle
buzzier_bees:black_candle
buzzier_bees:red_candle
buzzier_bees:green_candle
buzzier_bees:brown_candle
buzzier_bees:blue_candle
buzzier_bees:purple_candle
buzzier_bees:cyan_candle
buzzier_bees:light_gray_candle
buzzier_bees:gray_candle
buzzier_bees:pink_candle
buzzier_bees:lime_candle
buzzier_bees:blue_orchid_scented_candle
buzzier_bees:dandelion_scented_candle
buzzier_bees:cornflower_scented_candle
buzzier_bees:lily_of_the_valley_scented_candle
buzzier_bees:oxeye_daisy_scented_candle
buzzier_bees:poppy_scented_candle
buzzier_bees:white_tulip_scented_candle
buzzier_bees:orange_tulip_scented_candle
buzzier_bees:pink_tulip_scented_candle
buzzier_bees:red_tulip_scented_candle
buzzier_bees:wither_rose_scented_candle
buzzier_bees:white_clover_scented_candle
buzzier_bees:pink_clover_scented_candle
buzzier_bees:purple_hibiscus_scented_candle
buzzier_bees:magenta_hibiscus_scented_candle
buzzier_bees:pink_hibiscus_scented_candle
buzzier_bees:red_hibiscus_scented_candle
buzzier_bees:orange_hibiscus_scented_candle
buzzier_bees:yellow_hibiscus_scented_candle
buzzier_bees:white_lotus_flower_scented_candle
buzzier_bees:red_lotus_flower_scented_candle
buzzier_bees:dianthus_scented_candle
buzzier_bees:violet_scented_candle
buzzier_bees:cartwheel_scented_candle
buzzier_bees:bluebell_scented_candle
buzzier_bees:buttercup_scented_candle
buzzier_bees:warm_monkey_brush_scented_candle
buzzier_bees:hot_monkey_brush_scented_candle
buzzier_bees:scalding_monkey_brush_scented_candle
buzzier_bees:water_hyacinth_scented_candle
buzzier_bees:gilia_scented_candle
buzzier_bees:yucca_flower_scented_candle
buzzier_bees:pink_searocket_scented_candle
buzzier_bees:white_searocket_scented_candle
buzzier_bees:autumn_crocus_scented_candle
charm:gold_lantern
charm:gold_soul_lantern
charm:redstone_lantern
charm:glowball
buzzier_bees:honey_lamp
environmental:ice_lantern
quark:magma_bricks
quark:magma_bricks_slab
quark:magma_bricks_stairs
quark:magma_bricks_vertical_slab
quark:magma_bricks_wall
quark:red_crystal
quark:orange_crystal
quark:yellow_crystal
quark:green_crystal
quark:blue_crystal
quark:indigo_crystal
quark:violet_crystal
quark:white_crystal
quark:black_crystal
quark:red_crystal_pane
quark:orange_crystal_pane
quark:yellow_crystal_pane
quark:green_crystal_pane
quark:blue_crystal_pane
quark:indigo_crystal_pane
quark:violet_crystal_pane
quark:white_crystal_pane
quark:black_crystal_pane
quark:lit_lamp
minecraft:redstone_lamp
endergetic:glowing_poise_stem
endergetic:glowing_poise_wood
nether_extension:glowing_obsidian
quark:glowshroom_block
quark:myalite_crystal
quark:glowshroom
skinnedlanterns:skeleton_lantern_block
skinnedlanterns:skeleton_soul_lantern_block
skinnedlanterns:skeleton_ender_lantern_block
skinnedlanterns:wither_skeleton_lantern_block
skinnedlanterns:wither_skeleton_soul_lantern_block
skinnedlanterns:wither_skeleton_ender_lantern_block
skinnedlanterns:paper_white_lantern_block
skinnedlanterns:paper_white_soul_lantern_block
skinnedlanterns:paper_yellow_lantern_block
skinnedlanterns:paper_yellow_soul_lantern_block
skinnedlanterns:paper_orange_lantern_block
skinnedlanterns:paper_orange_soul_lantern_block
skinnedlanterns:paper_blue_lantern_block
skinnedlanterns:paper_pink_soul_lantern_block
skinnedlanterns:paper_pink_lantern_block
skinnedlanterns:paper_soul_lantern_block
skinnedlanterns:paper_lantern_block
skinnedlanterns:paper_green_soul_lantern_block
skinnedlanterns:paper_green_lantern_block
skinnedlanterns:paper_lime_soul_lantern_block
skinnedlanterns:paper_lime_lantern_block
skinnedlanterns:paper_cyan_soul_lantern_block
skinnedlanterns:paper_cyan_lantern_block
skinnedlanterns:paper_light_blue_soul_lantern_block
skinnedlanterns:paper_light_blue_lantern_block
skinnedlanterns:paper_blue_soul_lantern_block
skinnedlanterns:paper_brown_lantern_block
skinnedlanterns:paper_brown_soul_lantern_block
skinnedlanterns:paper_black_lantern_block
skinnedlanterns:paper_black_soul_lantern_block
skinnedlanterns:paper_gray_lantern_block
skinnedlanterns:paper_gray_soul_lantern_block
skinnedlanterns:paper_light_gray_lantern_block
skinnedlanterns:paper_light_gray_soul_lantern_block
skinnedlanterns:paper_magenta_lantern_block
skinnedlanterns:paper_magenta_soul_lantern_block
skinnedlanterns:paper_purple_lantern_block
skinnedlanterns:paper_purple_soul_lantern_block
skinnedlanterns:ornament_red_lantern_block
skinnedlanterns:ornament_green_soul_lantern_block
skinnedlanterns:ornament_green_lantern_block
skinnedlanterns:ornament_yellow_soul_lantern_block
skinnedlanterns:ornament_yellow_lantern_block
skinnedlanterns:ornament_magenta_soul_lantern_block
skinnedlanterns:ornament_magenta_lantern_block
skinnedlanterns:ornament_lime_soul_lantern_block
skinnedlanterns:ornament_lime_lantern_block
skinnedlanterns:ornament_purple_soul_lantern_block
skinnedlanterns:ornament_purple_lantern_block
skinnedlanterns:ornament_blue_soul_lantern_block
skinnedlanterns:ornament_red_soul_lantern_block
skinnedlanterns:ornament_blue_lantern_block
skinnedlanterns:ornament_light_blue_lantern_block
skinnedlanterns:ornament_white_soul_lantern_block
skinnedlanterns:ornament_gray_lantern_block
skinnedlanterns:ornament_light_blue_soul_lantern_block
skinnedlanterns:ornament_cyan_lantern_block
skinnedlanterns:ornament_gray_soul_lantern_block
skinnedlanterns:ornament_light_gray_lantern_block
skinnedlanterns:ornament_light_gray_soul_lantern_block
skinnedlanterns:ornament_pink_lantern_block
skinnedlanterns:ornament_cyan_soul_lantern_block
skinnedlanterns:ornament_pink_soul_lantern_block
skinnedlanterns:ornament_orange_lantern_block
skinnedlanterns:ornament_orange_soul_lantern_block
skinnedlanterns:ornament_brown_lantern_block
skinnedlanterns:ornament_brown_soul_lantern_block
skinnedlanterns:ornament_black_lantern_block
skinnedlanterns:ornament_black_soul_lantern_block
skinnedlanterns:ornament_white_lantern_block
supplementaries:sconce
supplementaries:sconce_soul
supplementaries:sconce_ender
supplementaries:firefly_jar
supplementaries:candelabra
supplementaries:redstone_illuminator
supplementaries:sconce_lever
endergetic:overworld_corrock_crown
endergetic:nether_corrock_crown
endergetic:end_corrock_crown
endergetic:acidian_lantern
endergetic:ender_campfire
endergetic:ender_lantern
endergetic:ender_torch
autumnity:ender_jack_o_lantern
autumnity:redstone_jack_o_lantern
autumnity:soul_jack_o_lantern
autumnity:large_jack_o_lantern_slice
autumnity:large_soul_jack_o_lantern_slice
autumnity:large_redstone_jack_o_lantern_slice
autumnity:large_ender_jack_o_lantern_slice
upgrade_aquatic:tooth_lantern
nether_extension:polished_glowstone
nether_extension:polished_glowstone_stairs
nether_extension:polished_glowstone_slab
nether_extension:polished_glowstone_vertical_slab
nether_extension:chiseled_polished_glowstone
nether_extension:shroomlamp
nether_extension:lit_shroomlamp
nether_extension:shroomfruit_crate
nether_extension:twisted_shroomlight
nether_extension:twisted_shroomfruit_crate
nether_extension:lit_twisted_shroomlamp
nether_extension:twisted_shroomlamp
charm:smooth_glowstone
lepton:stripped_glowshroom_hyphae_slab
lepton:stripped_glowshroom_hyphae_stairs
lepton:stripped_glowshroom_hyphae_vertical_slab
lepton:glowshroom_hyphae_slab
lepton:glowshroom_hyphae_stairs
lepton:glowshroom_hyphae_vertical_slab
lepton:stripped_glowshroom_hyphae_wall
lepton:glowshroom_hyphae_wall
quark:glowcelium
enhanced_mushrooms:glowshroom_planks
enhanced_mushrooms:glowshroom_stem
enhanced_mushrooms:stripped_glowshroom_stem
enhanced_mushrooms:stripped_glowshroom_hyphae
enhanced_mushrooms:glowshroom_hyphae
enhanced_mushrooms:glowshroom_slab
enhanced_mushrooms:glowshroom_stairs
enhanced_mushrooms:vertical_glowshroom_planks
enhanced_mushrooms:glowshroom_vertical_slab
enhanced_mushrooms:glowshroom_bookshelf
enhanced_mushrooms:glowshroom_fence
enhanced_mushrooms:glowshroom_beehive
enhanced_mushrooms:glowshroom_ladder
enhanced_mushrooms:glowshroom_pressure_plate
enhanced_mushrooms:glowshroom_fence_gate
enhanced_mushrooms:glowshroom_button
enhanced_mushrooms:glowshroom_trapdoor
enhanced_mushrooms:glowshroom_door`

**Comment by Vazkii** [comment]
Impressive, added

**Comment by e-motiv** [comment]
> Impressive, added

Added where? How? Help me.
Or is there already an addon for this meanwhile?
