### ISSUE TITLE
Inspirations disabled features can still be crafted

### ISSUE THREAD

**Issue by Samu03217** [Vazkii/crucia2-issues#18]
Some of the Inspirations features that are marked as "disabled" in the mod changes list, such as bookshelves or torch levers, can still be crafted and obtained in survival.
![IMG_20210207_101646](https://user-images.githubusercontent.com/78707262/107162002-b8bcd900-69a0-11eb-9d30-6c33902a7aa4.png)

**Comment by Vazkii** [comment]
Upon further inspection, the recipe disables only after a /reload, so I guess @knightminer isn't adjusting the recipe flags in time.

**Comment by Vazkii** [comment]
Temporarily fixed in the pack by forcing the recipes off with CT, but you should report this to inspirations.
