### ISSUE TITLE
JEI Redirect Suggestions

### ISSUE THREAD

**Issue by mfawc** [Vazkii/crucia2-issues#27]
A few things/phrasings I tried searching for while playing...

-"clothing"/"armor"
-"jobsite"
-"workstations"
-"tools" not sure if this one is already supported? seems to just bring up the vanilla tools + knifes
-"fuel"

**Comment by Vazkii** [comment]
I'm gonna skip on fuel cuz going through everything that can be used as fuel would take like 20 years, but I'll sort the other ones out.
