### ISSUE TITLE
[Suggestion] Outer End mod

### ISSUE THREAD

**Issue by MobiusFlip** [Vazkii/crucia2-issues#36]
The [Outer End](https://www.curseforge.com/minecraft/mc-mods/the-outer-end) would fit perfectly in this pack and help make the End a more interesting and vibrant place to explore. It's built to be compatible with Endergetic and includes the extra wood block types most Abnormals mods do for its new wood (bookshelves, vertical slabs, chests, etc). It does change the amount of health the Ender Dragon has and the recipe for end crystals, but the dragon health is configurable (and the end crystal recipe can be changed back with crafttweaker if it's not wanted).

**Comment by Vazkii** [comment]
I think we're already too far into the pack to add something like this.
