### ISSUE TITLE
Duplicate Rice items, also affects villager trades

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#45]
There appear to be two different rice items, one from environmental, which is what is found in villager trades, and the rice item from farmer's delight, and is the only one i've seen in the world - should these be unified?
They use different item icons, suggesting different items entirely.

**Comment by Vazkii** [comment]
The environmental rice is going to be removed before release, I've been told, so this is a non issue.

**Comment by kaeebonrai** [comment]
![javaw_2021-03-01_13-53-25](https://user-images.githubusercontent.com/723371/109448321-98f76d00-7a95-11eb-8237-66fdc645d6c5.png)
looks like this might be still an issue.
