### ISSUE TITLE
Description of default minecraft cake is both inconsistent and inaccurate

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#51]
Default minecraft cake description is "Can be stacked" when it cannot be, and none of the other cakes have matching descriptions, and also cannot be stacked
![javaw_2021-02-13_23-58-12](https://user-images.githubusercontent.com/723371/107851151-a850a680-6e57-11eb-99c5-25b524a68563.png)

**Comment by Vazkii** [comment]
I have no idea what mod is doing this lmao

**Comment by MobiusFlip** [comment]
Don't know what the mod is but "can be stacked" refers to the fact that you can place cake on top of cake to make a tiered cake, not that it stacks in your inventory.

**Comment by Vazkii** [comment]
oh ffs that makes sense, I should change the text so it's more apparent
