### ISSUE TITLE
unsynched entities (snail)

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#52]
one user on my home server cannot  see or interact with snails, I can see and interact with them, but they cannot even after spawning 2 in with spawn eggs. I can see and interact with these just fine. we have restarted the server, moved into a different dimension, and back, no difference in behavior
![unknown](https://user-images.githubusercontent.com/723371/107857214-e9a77d00-6e7c-11eb-93fd-1affd9fa7618.png)
![javaw_2021-02-14_04-28-21](https://user-images.githubusercontent.com/723371/107857233-21aec000-6e7d-11eb-80d6-ed44782fc71a.jpg)

**Comment by Vazkii** [comment]
I suggest you report this to autumnity
