### ISSUE TITLE
[Suggestion] Add modded fish to Forge:Raw_Fish tag

### ISSUE THREAD

**Issue by TDarkShadow** [Vazkii/crucia2-issues#55]
Modpack version: Beta 10.
Certain modded (raw) fish is missing from <tag:items:forge:raw_fishes>.
This include Koi (Enviromental) and Raw Pike (Upgrade Aquatic).

**Comment by Vazkii** [comment]
What does this affect?

**Comment by TDarkShadow** [comment]
It mainly affects recipes where it calls for a raw fish, like Squid Ink Pasta or Fish Stew, but fishes like Pike can't be used since it's not part of the tag.

![afbeelding](https://user-images.githubusercontent.com/5389859/108646635-dddc3c00-74b6-11eb-94c2-f63774975190.png)
(tropical fish and raw cod can be used for these recipes but not Pike.)
