### ISSUE TITLE
[Bug] Boiled Purple Pickerelweed shows twice in Smoking recipe category

### ISSUE THREAD

**Issue by TDarkShadow** [Vazkii/crucia2-issues#57]
Modpack version: Beta 10.
![javaw_MAorCDuuV0](https://user-images.githubusercontent.com/5389859/107880582-0e810c00-6ee0-11eb-91e6-d03fc87c7823.png)

**Comment by Vazkii** [comment]
Worth reporting to Upgrade Aquatic. It's pretty inconsequential in the context of the pack.

**Comment by TDarkShadow** [comment]
Issue has been fixed. https://github.com/team-abnormals/upgrade-aquatic/issues/253
