### ISSUE TITLE
[Bug] 4x chest recipes that use logs result in vanilla chests

### ISSUE THREAD

**Issue by pedroHLabrador** [Vazkii/crucia2-issues#58]
Version: Beta 10

Abundance
![image](https://user-images.githubusercontent.com/79051904/107881265-5d1fad80-6ec2-11eb-8ed6-65810fcdfeb9.png)

Atmospheric
![image](https://user-images.githubusercontent.com/79051904/107881115-8986fa00-6ec1-11eb-9f2b-3caba848f509.png)
![image](https://user-images.githubusercontent.com/79051904/107881139-be934c80-6ec1-11eb-8a0c-b627de47d315.png)
![image](https://user-images.githubusercontent.com/79051904/107881149-c81cb480-6ec1-11eb-9850-1edc5eb6ce01.png)

Bayou Blues
![image](https://user-images.githubusercontent.com/79051904/107881205-1f228980-6ec2-11eb-9961-706dac3b6d09.png)

Enhanced Mushrooms
![image](https://user-images.githubusercontent.com/79051904/107881325-a1ab4900-6ec2-11eb-8ec8-9a7e3e8589a4.png)
![image](https://user-images.githubusercontent.com/79051904/107881330-a839c080-6ec2-11eb-85a3-a91cf3886aae.png)
![image](https://user-images.githubusercontent.com/79051904/107881372-d8815f00-6ec2-11eb-8022-f8736bfbd261.png)

Environmental
![image](https://user-images.githubusercontent.com/79051904/107881215-29dd1e80-6ec2-11eb-94c6-246dca51a0ce.png)

Upgrade Aquatic
![image](https://user-images.githubusercontent.com/79051904/107881345-b851a000-6ec2-11eb-99c3-5186cbb447ab.png)
![image](https://user-images.githubusercontent.com/79051904/107881352-c0114480-6ec2-11eb-9df2-e3d4b3365008.png)

Note: Only Environmental's Willow and Abundance's Redbud chest recipes using their respective logs seem to be bugged. The others (Cherry and Wisteria from environmental and Jacaranda from Abundance) are working properly. Recipes using Vanilla and Endergetic Expansion's logs are working.

The crafting recipes using planks still work, except for the Red Mushroom Chest one using Enhanced Mushroom's planks.

**Comment by Vazkii** [comment]
Fixed in quark
