### ISSUE TITLE
Paragliders in Towers of The Wild are not guaranteed as intended 

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#60]
I’ve been to two towers of the wild thus far, in a 10k by 10k range, and neither has contained a paraglider.
![088CA60F-EEA1-4F21-95BF-D050EE6B4A23](https://user-images.githubusercontent.com/723371/107984240-7128f380-7017-11eb-9db0-2521e9c14084.png)

**Comment by exastencil** [comment]
Also encountered a tower, no waystone and no paraglider. Only one I've found so far.

Seed: -3450475304370813039
Location: 55 97 478

**Comment by Vazkii** [comment]
I've been to a bunch already and I can't find any without a paraglider. I wonder if the datapack didn't load properly for you?

**Comment by kaeebonrai** [comment]
still no paragliders in latest version, neither in normal towers of the wild, nor ocean towers, nor jungle tower, nor ice,
logs suggest crucial_data datapack loads fine.
![javaw_2021-02-21_12-22-56](https://user-images.githubusercontent.com/723371/108613212-c4e47400-743f-11eb-951f-375fcfcb465a.jpg)
![unknown](https://user-images.githubusercontent.com/723371/108613233-e9d8e700-743f-11eb-8aea-0c4c9e342f71.png)
![unknown2](https://user-images.githubusercontent.com/723371/108613295-653a9880-7440-11eb-854a-5231b624c510.png)
![javaw_2021-02-21_12-23-17](https://user-images.githubusercontent.com/723371/108613213-c615a100-743f-11eb-9029-68fa81b7d9cd.png)
![unknown](https://user-images.githubusercontent.com/723371/108613257-155bd180-7440-11eb-91ba-39a04732925c.png)

**Comment by Megamagma** [comment]
foudn two towers in the latest version, neither had a paraglider, and i was actually able to pick up the waystone. was told to make an issue but saw this and decided it would probably be best to put it here.
![2021-02-24_18 16 33](https://user-images.githubusercontent.com/79612458/109083815-9b904600-76d4-11eb-8ee8-d8e2951e1a5c.png)
![2021-02-24_18 16 59](https://user-images.githubusercontent.com/79612458/109083817-9c28dc80-76d4-11eb-9f71-5003863cd9d7.png)
![2021-02-24_19 07 22](https://user-images.githubusercontent.com/79612458/109083819-9e8b3680-76d4-11eb-812b-33c65960c769.png)
