### ISSUE TITLE
Server Crash when fighting pillagers in village raids or in woodland mansion

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#63]
When on my server we have fought pillagers/illagers in a village raid or a woodland mansion, it has caused a server crash, Raids are unable to be completed due to continual crashing.
[debug.log](https://github.com/Vazkii/crucia2-issues/files/6011231/debug.log)
[latest.log](https://github.com/Vazkii/crucia2-issues/files/6011232/latest.log)
[crafttweaker.log](https://github.com/Vazkii/crucia2-issues/files/6011234/crafttweaker.log)
[crash-2021-02-13_06.56.47-server.txt](https://github.com/Vazkii/crucia2-issues/files/6011236/crash-2021-02-13_06.56.47-server.txt)

**Comment by Vazkii** [comment]
Disabling using totem from the inventory for now.
