### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jason-pollak** [Vazkii/crucia2-issues#7]
<img width="326" alt="Screen Shot 2021-02-04 at 5 37 58 PM" src="https://user-images.githubusercontent.com/45409046/106977751-c7409180-670f-11eb-807d-2001a79f5ee8.png">
"Keep **ind** mind..."

**Comment by jason-pollak** [comment]
<img width="326" alt="Screen Shot 2021-02-04 at 5 39 28 PM" src="https://user-images.githubusercontent.com/45409046/106977865-f951f380-670f-11eb-8895-6883316dc8ad.png">
"Soul Camprifres"

**Comment by jason-pollak** [comment]
Missing apostrophe in "you'll"
![Uploading Screen Shot 2021-02-04 at 10.40.08 PM.png…]()

**Comment by Vazkii** [comment]
The missing apostrophe is a JEI bug, it doesn't show apostrophes for some reason.

Other ones have been fixed!
