### ISSUE TITLE
crates immediately crash server on opening

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#70]
[crash-2021-02-21_02.14.37-server.txt](https://github.com/Vazkii/crucia2-issues/files/6017076/crash-2021-02-21_02.14.37-server.txt)
[debug.log](https://github.com/Vazkii/crucia2-issues/files/6017077/debug.log)
[latest.log](https://github.com/Vazkii/crucia2-issues/files/6017078/latest.log)
[crafttweaker.log](https://github.com/Vazkii/crucia2-issues/files/6017079/crafttweaker.log)

**Comment by Vazkii** [comment]
Fixed
