### ISSUE TITLE
Crashing upon launch using Apple silicon Macs

### ISSUE THREAD

**Issue by hyl1cs** [Vazkii/crucia2-issues#74]
[crash-2021-02-22_17.32.59-client.txt](https://github.com/Vazkii/crucia2-issues/files/6026308/crash-2021-02-22_17.32.59-client.txt)
Crash log attached above, fixed by adding "-Dfml.earlyprogresswindow=false" to the JVM arguments, consider adding this by default if possible!

**Comment by Vazkii** [comment]
Can a pack even customize JVM arguments at all?
