### ISSUE TITLE
[Bug] Egg crates cannot be crafted/uncrafted

### ISSUE THREAD

**Issue by pedroHLabrador** [Vazkii/crucia2-issues#75]
Crucial 2 beta version 12
![image](https://user-images.githubusercontent.com/79051904/109176856-0047b100-7766-11eb-9eda-0d7f1a9b4fd9.png)
![image](https://user-images.githubusercontent.com/79051904/109176916-10f82700-7766-11eb-8e5d-255f69300b65.png)
![image](https://user-images.githubusercontent.com/79051904/109176983-1eadac80-7766-11eb-8b12-ee733ae60d9f.png)
![image](https://user-images.githubusercontent.com/79051904/109176944-16ee0800-7766-11eb-9f0d-4444e6f64eb4.png)

The recipes don't show up on JEI either when clicked on each of these respective items.

**Comment by Vazkii** [comment]
I can see them fine in my instance. Did you change anything?
