### ISSUE TITLE
Items Missing "Equipment" Tag

### ISSUE THREAD

**Issue by MobiusFlip** [Vazkii/crucia2-issues#8]
The following items do not have the "crucial:categories/equipment" tag and don't show when "equipment" is typed into JEI:

* Iron Helmet
* Iron Boots
* Golden Sword
* Golden Leggings
* Golden Boots
* Netherite Shovel
* Netherite Hoe
* Netherite Leggings

**Comment by Vazkii** [comment]
Fixed
