### ISSUE TITLE
Fried eggs present in two mods (conflicting recipes)

### ISSUE THREAD

**Issue by iGalaxyYT** [Vazkii/crucia2-issues#9]
Both Environmental and Farmer's Delight have a fried egg item, and they have overlapped recipes. (environmental:fried_egg and farmersdelight:fried_egg respectively)

![image](https://user-images.githubusercontent.com/22878174/106980790-ab3fee80-6715-11eb-916f-c01fc22f20df.png)
![image](https://user-images.githubusercontent.com/22878174/106980859-cf9bcb00-6715-11eb-9498-7496ca4d8e79.png)
![image](https://user-images.githubusercontent.com/22878174/106980876-d4607f00-6715-11eb-806a-ec7cec4e0036.png)

**Comment by Vazkii** [comment]
Fixed
